#!/usr/bin/env python

import glob

Import('env')

sources = glob.glob("src/*.cpp") + ["register_types.cpp"]

env_actors = env.Clone()
env_actors.Append(CXXCFLAGS=["-Iinclude/", "-O2", "-std=c++11", "-Werror", "-Wall"])
env_actors.Append(CPPPATH=["include"])

if ARGUMENTS.get("actors_shared", "no") == "yes":
    env_actors.Append(CXXFLAGS="-fPIC")

    env_actors["LIBS"] = []

    shared_lib = env_actors.SharedLibrary(target="#bin/actors", source=sources)


    shared_lib_shim = shared_lib[0].name.rsplit(".", 1)[0]
    env.Append(LIBS=[shared_lib_shim])
    env.Append(LIBPATH="#bin")

else:
    env_actors.add_source_files(env.modules_sources, sources)
